### ISSUE TITLE
Combine date/time blocks

### ISSUE THREAD

**Issue by rosshadden** [acleverpun/i3-blocks-contrib#10]
Why did we make separate blocks for date and time?  They both pass a format string to `date`, the only difference is the default string.  We should just combine these into one datetime block, and use two instances of it.

**Comment by rawsp33d** [comment]
I guess there's slightly more to it than I was thinking.  They both have defaults as well as "short" formats.  Since we don't allow users to configure the "short" output, this would be awkward at best in a combined block.
