### ISSUE TITLE
how do I change from Fahrenheit to Celsius

### ISSUE THREAD

**Issue by elhackerlibre** [acleverpun/i3-blocks-contrib#11]
Hi. its great weather this script , but I'm not very skilled programming in bash , but I would like to know which variable can change in your scripts to make the change from Fahrenheit to Celsius ?

I thought that if I changed the variable  -F to -C, in the lines
**weather = " $ (echo " $ SITE " | awk -F \ '
temp = " $ (echo " $ SITE " | awk -F \**
But it does not work

They can help me to modify your scripts to work with the format of my city weather?
Please...

**Comment by rawsp33d** [comment]
This isn't a great answer, but you can just convert it to Celsius with maths.

```
T(°C) = (T(°F) - 32) × 5/9
```

That is, to convert the temperature to Celsius, you subtract `32` from the Fahrenheit value and multiply it by `5 / 9`.

I modified the code just now to make it easy for you to change on your end.  All you have to do is insert the following line somewhere after `temp` is set:

``` bash
temp=$(echo "($temp - 32) * 5/9" | bc)
```

The weather block is our worst one by far, in terms of how crappy the code is.  We have an issue already created to remind us to completely rewrite it ( #2 ), and will get to it eventually.

**Comment by elhackerlibre** [comment]
Oh thank you very much for answering ...
I'll try to see how it works!
I have caused some laughter the comment of your code sucks ...
But to me it has worked very well. And I congratulate you for the great work they do ...

**Comment by rawsp33d** [comment]
Sure, I am happy to help.  I am going to close this for now, but let me know if you have more questions.
