### ISSUE TITLE
Stateful blocks

### ISSUE THREAD

**Issue by rosshadden** [acleverpun/i3-blocks-contrib#8]
We need to implement an ecosystem for having blocks persist.  Likely simply storing files in `~/.cache`, or even a directory that is actually meant to persist.

**Comment by oppenlander** [comment]
There is the new [persist](https://github.com/vivien/i3blocks/blob/master/i3blocks.1.ronn#L103) option we haven't done anything with.

**Comment by rawsp33d** [comment]
:+1:
